repos:
  - repo: local
    hooks:
      - id: build-presentations
        name: Build Presentations
        entry: bash -c 'source ../.venv/bin/activate && cd docs && make presentations'
        language: system
        types: [markdown]
        files: ^docs/.*\.md$
        pass_filenames: false
        always_run: true
        stages: [commit]
        additional_dependencies: [marp-cli]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
