# .readthedocs.yml

version: 2

# Build configuration
build:
  os: ubuntu-22.04  # Set the OS for the build environment, e.g., Ubuntu 22.04
  tools:
    python: "3.8"   # Specify the Python version

# Sphinx documentation configuration
sphinx:
  configuration: docs/conf.py

# Optionally build your docs in additional formats such as PDF and ePub
formats:
  - pdf
  - epub

# Specify the Python version and the dependencies
# Specify the Python version and the dependencies
python:
  install:
    - requirements: requirements.txt
    - method: pip
      path: .
