name: Build & Deploy Documentation

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          cache: "pip"

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"

      - name: Create virtual environment and install dependencies
        run: |
          # Create virtual environment
          uv venv
          # Activate virtual environment and install from pyproject.toml
          source .venv/bin/activate
          # Install additional docs-specific dependencies
          uv add sphinx sphinx-rtd-theme myst-parser

      - name: Setup Node.js for Marp
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install Marp CLI
        run: npm install -g @marp-team/marp-cli

      - name: Build Sphinx HTML docs
        working-directory: docs
        run: |
          # Activate virtual environment for Sphinx build
          source ../.venv/bin/activate
          make clean
          make html
          # Ensure Pages doesn't run Jekyll
          touch build/html/.nojekyll

      - name: Copy static files
        working-directory: docs
        run: |
          echo "Current directory: $(pwd)"
          echo "Source static exists: $(ls -la source/static/)"
          echo "Build html exists: $(ls -la build/html/)"
          if [ -d source/static ]; then
            echo "Copying static files..."
            cp -rv source/static build/html/
            echo "After copy, build/html/static contains:"
            ls -la build/html/static/
          else
            echo "source/static directory not found"
          fi

      - name: Build HTML presentation in CI
        working-directory: docs
        run: |
          echo "Building HTML presentation in CI..."
          marp source/nczarr_viewer_presentation.md --output build/html/nczarr_viewer_presentation.html --theme source/static/styles/edito-marp.css --allow-local-files
          echo "✅ HTML presentation built successfully!"
          echo "Building PDF presentation in CI..."
          marp source/nczarr_viewer_presentation.md --output nczarr_viewer_presentation.pdf --theme source/static/styles/edito-marp.css --allow-local-files
          echo "✅ PDF presentation built successfully!"

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/build/html

  deploy:
    needs: build-docs
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
